### ISSUE TITLE
ques : Hooking AC with explorer

### ISSUE THREAD

**Issue by Vipin2003** [krlvm/AccentColorizer#37]
Is there any way or plans for hooking AccentColorizer with explorer like SAB has did. Becoz sometimes it takes long to autostart and sometimes won't work like after intalling Rectify11. So, it would be great if it is possible to do this.

Bcoz SAB doesn't provide the progress bar colorization feature with its implementation. And, it will solve colorization issues with many locations in explorer.

It would be graet if it is planned in future.

**Comment by krlvm** [comment]
AccentColorizer does not use and does not need any hooking, it uses documented [`SetSysColors`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setsyscolors) function to set some "simple" colors (e.g. highlight color) and it uses documented [`GetThemeBitmap`](GetThemeBitmap) function with `GBF_DIRECT` flag for direct theme bitmap access and then overwrites it.

I don't see the connection between startup time and hooking with explorer. If by hooking you suggest to just inject into the explorer process, then it would slow down its startup time, as AccentColorizer startup time will be added to it - but actually, AccentColorizer startup time is negligible, any slowness you feel is most likely the time it takes for the change to propagate, I'll release a version with small optimizations soon though.

Again, if by hooking you mean just injecting AC into the explorer process, it would not "solve colorization issues with many locations in explorer" such as Ribbon bar - we need to know, what to hook and do a lot of reverse-engineering of the explorer to learn what should we hook and how, not to mention the fact that for small advantages, the complexity of the program will increase greatly, and there will also be a compatibility problem with previous versions of Windows. So I don't think it would be beneficial.

I see what Rectify11 does is installing a custom visual styles (.msstyles theme), so, most likely, some bitmaps it replaces are too dim - for colorization AC converts RGB into a more suitable HSV color representation and changes its hue to the current accent color's hue, but with marginal hue values it works bad, e.g. it makes everything dark red if accent color is too dark, so that might be the case.

**Comment by krlvm** [comment]
Indeed, the colorization takes almost a second on my PC, what is long enough. 
I was able to reduce this time four times in [version 1.2](https://github.com/krlvm/AccentColorizer/releases/tag/v1.2.0).
